
-- CRIAR BANCO: MANUTENCAO_EQUIPAMENTOS

CREATE DATABASE IF NOT EXISTS manutencao_equipamentos;
USE manutencao_equipamentos;


-- TABELA STATUS

CREATE TABLE STATUS (
    idStatus INT AUTO_INCREMENT PRIMARY KEY,
    nomeStatus VARCHAR(30) NOT NULL
);


-- TABELA USUARIO

CREATE TABLE USUARIO (
    idUsuario INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    telefone VARCHAR(20),
    senhaHash VARCHAR(256) NOT NULL,
    senhaSalt VARCHAR(64) NOT NULL,
    tipo ENUM('CLIENTE','FUNCIONARIO') NOT NULL,
    isDelete BOOLEAN DEFAULT FALSE
);


-- TABELA ENDERECO

CREATE TABLE ENDERECO (
    idEndereco INT AUTO_INCREMENT PRIMARY KEY,
    cep VARCHAR(9) NOT NULL,
    logradouro VARCHAR(100) NOT NULL,
    numero VARCHAR(10),
    complemento VARCHAR(50),
    bairro VARCHAR(50),
    cidade VARCHAR(50) NOT NULL,
    estado VARCHAR(2) NOT NULL
);


-- TABELA CLIENTE

CREATE TABLE CLIENTE (
    idCliente INT PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    idEndereco INT NOT NULL,
    FOREIGN KEY (idCliente) REFERENCES USUARIO(idUsuario),
    FOREIGN KEY (idEndereco) REFERENCES ENDERECO(idEndereco)
);


-- TABELA FUNCIONARIO

CREATE TABLE FUNCIONARIO (
    idFuncionario INT PRIMARY KEY,
    cpf VARCHAR(11) NOT NULL UNIQUE,
    dataNascimento DATE,
    FOREIGN KEY (idFuncionario) REFERENCES USUARIO(idUsuario)
);


-- TABELA CATEGORIA

CREATE TABLE CATEGORIA (
    idCategoria INT AUTO_INCREMENT PRIMARY KEY,
    nomeCategoria VARCHAR(50) NOT NULL,
    isDelete BOOLEAN DEFAULT FALSE
);
